name: CI/CD Push Images and Deploy the Web application

on:
  push:
    branches:
      - "main"

env:
    AZURE_WEBAPP_NAME: aspnet-webapp-demo-01
    AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
    Build-Images:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}
    Deployment:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Setup .Net environment with specific version
              uses: actions/setup-dotnet@v3
              with:
                dotnnet-version: '7.0.x'

            - name: Restore
              run: dotnet restore ./cicd-deploy-asp-webapp.csproj

            - name: Build at Release mode
              run: dotnet build ./cicd-deploy-asp-webapp.csproj --configuration Release --no-restore

            - name: Publish
              run: dotnet publish ./cicd-deploy-asp-webapp.csproj --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
    
            - name: Deployment
              uses: azure/webapps-deploy@v2
              with:
                app-name: ${{ env.AZURE_WEBAPP_NAME }}
                publish-profile: ${{ secrets.ASP_NET_CORE_WEBAPP_01_PUBLISH_PROFILE }}
                package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
